project:
  type: book
  pre-render: R/setup.R

callout-appearance: simple
# see this quarto discussion issue for info on lua filter
# https://github.com/quarto-dev/quarto-cli/discussions/2869#discussioncomment-3886253
filters: 
 - chapters/lua/callouts.lua

execute:
  freeze: auto  
  echo: true 
  dev: "ragg_png"
  dpi: 740 
  out.width: "80%"
  fig.width: 6
  fig.asp: 0.618
  fig.retina: 3
  fig.align: "center"
  fig.show: "hold"
  
book:
  title: "Causal Inference in R"
  author: ["Malcolm Barrett", "Lucy D'Agostino McGowan", "Travis Gerke"]
  date: "today"
  repo-url: https://github.com/malcolmbarrett/causal-inference-in-r
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
  
    - part: Asking Causal Questions
      chapters:
      - chapters/01-casual-to-causal.qmd
      - chapters/02-whole-game.qmd
      - chapters/03-po-counterfactuals.qmd
      - chapters/04-dags.qmd
      - chapters/05-not-just-a-stats-problem.qmd
      - chapters/06-stats-models-ci.qmd
  
    - part: The Design Phase
      chapters:
      - chapters/07-prep-data.qmd
      - chapters/08-propensity-scores.qmd
      - chapters/09-evaluating-ps.qmd
  
    - part: Estimating Causal Effects
      chapters:
      - chapters/10-estimands.qmd
      - chapters/11-outcome-model.qmd
      - chapters/12-other-exposures.qmd
      - chapters/13-g-comp.qmd
      - chapters/14-interaction.qmd
      - chapters/15-missingness-and-measurement.qmd
      - chapters/16-sensitivity.qmd
      - chapters/17-mediation.qmd
      - chapters/18-longitudinal.qmd
      - chapters/19-time-to-event.qmd
      - chapters/20-doubly-robust.qmd
      - chapters/21-machine-learning.qmd
      - chapters/22-iv-and-friends.qmd
      - chapters/23-diff-in-diff.qmd
      - chapters/24-evidence.qmd
  
    - chapters/99-references.qmd
  appendices: 
    - appendices/A-bootstrap.qmd
bibliography: citations.bib

format:
  html:
    code-link: true
    tbl-cap-location: bottom
    theme:
      - cosmo
      - style.scss
    include-in-header: "plausible.html"
  pdf:
    tbl-cap-location: bottom
    documentclass: krantz
    link-citations: true
    colorlinks: true
    lot: true
    lof: true
    includes:
      in_header: latex/preamble.tex
      before_body: latex/before_body.tex
      after_body: latex/after_body.tex

editor_options:
  markdown:
    wrap: sentence
    canonical: true
    
